
export const environment = {
   // This file is generated by set-env.ts file. Changes in this file will be overwritten. 
   // Change environment variables in .env file.  
   
   production: false,
   REGION: "",
   COGNITO: {
      USER_POOL_ID: "",
      CLIENT_ID: "",
      IDENTITY_POOL_ID: ""
   },
   S3: {
      BUCKET_NAME: ""
   },
   CLOUDFRONT: {
      IMAGE_ENDPOINT: "",
      IMAGE_AUTH_ENDPOINT: "",
      IMAGE_AUTH_LOGOUT: ""
   }
};
